# Generated by Django 6.0.3 on 2026-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_document_entities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
