# Generated by Django 6.0.3 on 2026-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_document_options_alter_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AlterField(
            model_name='document',
            name='entities',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='document',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
