# Generated by Django 6.0.3 on 2026-04-01 17:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_document_file_alter_document_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=accounts.models.upload_to_user),
        ),
    ]
