# Generated by Django 6.0.3 on 2026-04-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_document_options_document_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
